name: manimate
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.7.22=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ipykernel=6.25.1=pyh71e2992_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py38h578d9bd_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1l=h7f98852_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=py38h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.22.0
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - altair==5.0.1
      - annotated-types==0.5.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.2
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.14.4
      - dill==0.3.7
      - einops==0.6.1
      - exceptiongroup==1.1.3
      - fastapi==0.103.0
      - ffmpy==0.3.1
      - filelock==3.12.2
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.41.2
      - gradio-client==0.5.0
      - grpcio==1.57.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.5
      - lightning-utilities==0.9.0
      - lit==16.0.6
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.8.0.76
      - orjson==3.9.5
      - pandas==2.0.3
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==4.24.2
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pydub==0.25.1
      - pyparsing==3.0.9
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.7
      - pytz==2023.3
      - pyyaml==6.0.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rpds-py==0.9.2
      - rsa==4.9
      - safetensors==0.3.3
      - semantic-version==2.10.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tokenizers==0.13.3
      - toolz==0.12.0
      - torchmetrics==1.1.0
      - tqdm==4.66.1
      - transformers==4.32.0
      - triton==2.0.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - uvicorn==0.23.2
      - websockets==11.0.3
      - werkzeug==2.3.7
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2
      - decord
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.3
      - timm
      - scipy
      - scikit-image
      - av
      - imgaug
      - lpips
      - ffmpeg-python
      - torch==2.0.1
      - torchvision==0.15.2
      - xformers==0.0.22
      - diffusers==0.21.4
prefix: /home/tiger/miniconda3/envs/manimate